export const attendance = [
  // 1회차 - OT 및 과정 소개
  { id: 1, sessionId: 1, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 2, sessionId: 1, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 3, sessionId: 1, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 4, sessionId: 1, memberId: 4, memberName: '최유진', status: '지각' },
  { id: 5, sessionId: 1, memberId: 5, memberName: '정하은', status: '출석' },
  { id: 6, sessionId: 1, memberId: 6, memberName: '강도현', status: '출석' },
  { id: 7, sessionId: 1, memberId: 7, memberName: '윤서아', status: '출석' },
  { id: 8, sessionId: 1, memberId: 8, memberName: '임재혁', status: '결석' },
  { id: 9, sessionId: 1, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 10, sessionId: 1, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 11, sessionId: 1, memberId: 11, memberName: '신예은', status: '출석' },
  { id: 12, sessionId: 1, memberId: 12, memberName: '조민재', status: '출석' },
  { id: 13, sessionId: 1, memberId: 13, memberName: '배수빈', status: '지각' },
  { id: 14, sessionId: 1, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 15, sessionId: 1, memberId: 15, memberName: '황나윤', status: '출석' },
  { id: 16, sessionId: 1, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 17, sessionId: 1, memberId: 17, memberName: '권다인', status: '출석' },
  { id: 18, sessionId: 1, memberId: 18, memberName: '송태민', status: '공결' },
  { id: 19, sessionId: 1, memberId: 19, memberName: '노지현', status: '출석' },
  { id: 20, sessionId: 1, memberId: 20, memberName: '문성호', status: '출석' },

  // 2회차 - 기초 이론
  { id: 21, sessionId: 2, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 22, sessionId: 2, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 23, sessionId: 2, memberId: 3, memberName: '박지훈', status: '지각' },
  { id: 24, sessionId: 2, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 25, sessionId: 2, memberId: 5, memberName: '정하은', status: '출석' },
  { id: 26, sessionId: 2, memberId: 6, memberName: '강도현', status: '결석' },
  { id: 27, sessionId: 2, memberId: 7, memberName: '윤서아', status: '출석' },
  { id: 28, sessionId: 2, memberId: 8, memberName: '임재혁', status: '출석' },
  { id: 29, sessionId: 2, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 30, sessionId: 2, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 31, sessionId: 2, memberId: 11, memberName: '신예은', status: '지각' },
  { id: 32, sessionId: 2, memberId: 12, memberName: '조민재', status: '출석' },
  { id: 33, sessionId: 2, memberId: 13, memberName: '배수빈', status: '출석' },
  { id: 34, sessionId: 2, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 35, sessionId: 2, memberId: 15, memberName: '황나윤', status: '결석' },
  { id: 36, sessionId: 2, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 37, sessionId: 2, memberId: 17, memberName: '권다인', status: '출석' },
  { id: 38, sessionId: 2, memberId: 18, memberName: '송태민', status: '출석' },
  { id: 39, sessionId: 2, memberId: 19, memberName: '노지현', status: '출석' },
  { id: 40, sessionId: 2, memberId: 20, memberName: '문성호', status: '출석' },

  // 3회차 - 실습 1
  { id: 41, sessionId: 3, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 42, sessionId: 3, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 43, sessionId: 3, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 44, sessionId: 3, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 45, sessionId: 3, memberId: 5, memberName: '정하은', status: '결석' },
  { id: 46, sessionId: 3, memberId: 6, memberName: '강도현', status: '출석' },
  { id: 47, sessionId: 3, memberId: 7, memberName: '윤서아', status: '출석' },
  { id: 48, sessionId: 3, memberId: 8, memberName: '임재혁', status: '지각' },
  { id: 49, sessionId: 3, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 50, sessionId: 3, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 51, sessionId: 3, memberId: 11, memberName: '신예은', status: '출석' },
  { id: 52, sessionId: 3, memberId: 12, memberName: '조민재', status: '공결' },
  { id: 53, sessionId: 3, memberId: 13, memberName: '배수빈', status: '출석' },
  { id: 54, sessionId: 3, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 55, sessionId: 3, memberId: 15, memberName: '황나윤', status: '출석' },
  { id: 56, sessionId: 3, memberId: 16, memberName: '전승우', status: '지각' },
  { id: 57, sessionId: 3, memberId: 17, memberName: '권다인', status: '출석' },
  { id: 58, sessionId: 3, memberId: 18, memberName: '송태민', status: '출석' },
  { id: 59, sessionId: 3, memberId: 19, memberName: '노지현', status: '출석' },
  { id: 60, sessionId: 3, memberId: 20, memberName: '문성호', status: '결석' },

  // 4회차 - 심화 이론
  { id: 61, sessionId: 4, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 62, sessionId: 4, memberId: 2, memberName: '이서연', status: '결석' },
  { id: 63, sessionId: 4, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 64, sessionId: 4, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 65, sessionId: 4, memberId: 5, memberName: '정하은', status: '출석' },
  { id: 66, sessionId: 4, memberId: 6, memberName: '강도현', status: '출석' },
  { id: 67, sessionId: 4, memberId: 7, memberName: '윤서아', status: '지각' },
  { id: 68, sessionId: 4, memberId: 8, memberName: '임재혁', status: '출석' },
  { id: 69, sessionId: 4, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 70, sessionId: 4, memberId: 10, memberName: '오준서', status: '공결' },
  { id: 71, sessionId: 4, memberId: 11, memberName: '신예은', status: '출석' },
  { id: 72, sessionId: 4, memberId: 12, memberName: '조민재', status: '출석' },
  { id: 73, sessionId: 4, memberId: 13, memberName: '배수빈', status: '출석' },
  { id: 74, sessionId: 4, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 75, sessionId: 4, memberId: 15, memberName: '황나윤', status: '출석' },
  { id: 76, sessionId: 4, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 77, sessionId: 4, memberId: 17, memberName: '권다인', status: '결석' },
  { id: 78, sessionId: 4, memberId: 18, memberName: '송태민', status: '출석' },
  { id: 79, sessionId: 4, memberId: 19, memberName: '노지현', status: '지각' },
  { id: 80, sessionId: 4, memberId: 20, memberName: '문성호', status: '출석' },

  // 5회차 - 팀 프로젝트 기획
  { id: 81, sessionId: 5, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 82, sessionId: 5, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 83, sessionId: 5, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 84, sessionId: 5, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 85, sessionId: 5, memberId: 5, memberName: '정하은', status: '출석' },
  { id: 86, sessionId: 5, memberId: 6, memberName: '강도현', status: '지각' },
  { id: 87, sessionId: 5, memberId: 7, memberName: '윤서아', status: '출석' },
  { id: 88, sessionId: 5, memberId: 8, memberName: '임재혁', status: '출석' },
  { id: 89, sessionId: 5, memberId: 9, memberName: '한소율', status: '결석' },
  { id: 90, sessionId: 5, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 91, sessionId: 5, memberId: 11, memberName: '신예은', status: '출석' },
  { id: 92, sessionId: 5, memberId: 12, memberName: '조민재', status: '출석' },
  { id: 93, sessionId: 5, memberId: 13, memberName: '배수빈', status: '출석' },
  { id: 94, sessionId: 5, memberId: 14, memberName: '류지안', status: '공결' },
  { id: 95, sessionId: 5, memberId: 15, memberName: '황나윤', status: '출석' },
  { id: 96, sessionId: 5, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 97, sessionId: 5, memberId: 17, memberName: '권다인', status: '출석' },
  { id: 98, sessionId: 5, memberId: 18, memberName: '송태민', status: '지각' },
  { id: 99, sessionId: 5, memberId: 19, memberName: '노지현', status: '출석' },
  { id: 100, sessionId: 5, memberId: 20, memberName: '문성호', status: '출석' },

  // 6회차 - 실습 2
  { id: 101, sessionId: 6, memberId: 1, memberName: '김민수', status: '지각' },
  { id: 102, sessionId: 6, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 103, sessionId: 6, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 104, sessionId: 6, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 105, sessionId: 6, memberId: 5, memberName: '정하은', status: '출석' },
  { id: 106, sessionId: 6, memberId: 6, memberName: '강도현', status: '출석' },
  { id: 107, sessionId: 6, memberId: 7, memberName: '윤서아', status: '출석' },
  { id: 108, sessionId: 6, memberId: 8, memberName: '임재혁', status: '결석' },
  { id: 109, sessionId: 6, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 110, sessionId: 6, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 111, sessionId: 6, memberId: 11, memberName: '신예은', status: '출석' },
  { id: 112, sessionId: 6, memberId: 12, memberName: '조민재', status: '출석' },
  { id: 113, sessionId: 6, memberId: 13, memberName: '배수빈', status: '결석' },
  { id: 114, sessionId: 6, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 115, sessionId: 6, memberId: 15, memberName: '황나윤', status: '지각' },
  { id: 116, sessionId: 6, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 117, sessionId: 6, memberId: 17, memberName: '권다인', status: '출석' },
  { id: 118, sessionId: 6, memberId: 18, memberName: '송태민', status: '출석' },
  { id: 119, sessionId: 6, memberId: 19, memberName: '노지현', status: '공결' },
  { id: 120, sessionId: 6, memberId: 20, memberName: '문성호', status: '출석' },

  // 7회차 - 중간 발표
  { id: 121, sessionId: 7, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 122, sessionId: 7, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 123, sessionId: 7, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 124, sessionId: 7, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 125, sessionId: 7, memberId: 5, memberName: '정하은', status: '지각' },
  { id: 126, sessionId: 7, memberId: 6, memberName: '강도현', status: '출석' },
  { id: 127, sessionId: 7, memberId: 7, memberName: '윤서아', status: '결석' },
  { id: 128, sessionId: 7, memberId: 8, memberName: '임재혁', status: '출석' },
  { id: 129, sessionId: 7, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 130, sessionId: 7, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 131, sessionId: 7, memberId: 11, memberName: '신예은', status: '출석' },
  { id: 132, sessionId: 7, memberId: 12, memberName: '조민재', status: '지각' },
  { id: 133, sessionId: 7, memberId: 13, memberName: '배수빈', status: '출석' },
  { id: 134, sessionId: 7, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 135, sessionId: 7, memberId: 15, memberName: '황나윤', status: '출석' },
  { id: 136, sessionId: 7, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 137, sessionId: 7, memberId: 17, memberName: '권다인', status: '출석' },
  { id: 138, sessionId: 7, memberId: 18, memberName: '송태민', status: '출석' },
  { id: 139, sessionId: 7, memberId: 19, memberName: '노지현', status: '출석' },
  { id: 140, sessionId: 7, memberId: 20, memberName: '문성호', status: '공결' },

  // 8회차 - 최종 발표 및 수료식
  { id: 141, sessionId: 8, memberId: 1, memberName: '김민수', status: '출석' },
  { id: 142, sessionId: 8, memberId: 2, memberName: '이서연', status: '출석' },
  { id: 143, sessionId: 8, memberId: 3, memberName: '박지훈', status: '출석' },
  { id: 144, sessionId: 8, memberId: 4, memberName: '최유진', status: '출석' },
  { id: 145, sessionId: 8, memberId: 5, memberName: '정하은', status: '출석' },
  { id: 146, sessionId: 8, memberId: 6, memberName: '강도현', status: '출석' },
  { id: 147, sessionId: 8, memberId: 7, memberName: '윤서아', status: '출석' },
  { id: 148, sessionId: 8, memberId: 8, memberName: '임재혁', status: '지각' },
  { id: 149, sessionId: 8, memberId: 9, memberName: '한소율', status: '출석' },
  { id: 150, sessionId: 8, memberId: 10, memberName: '오준서', status: '출석' },
  { id: 151, sessionId: 8, memberId: 11, memberName: '신예은', status: '결석' },
  { id: 152, sessionId: 8, memberId: 12, memberName: '조민재', status: '출석' },
  { id: 153, sessionId: 8, memberId: 13, memberName: '배수빈', status: '출석' },
  { id: 154, sessionId: 8, memberId: 14, memberName: '류지안', status: '출석' },
  { id: 155, sessionId: 8, memberId: 15, memberName: '황나윤', status: '출석' },
  { id: 156, sessionId: 8, memberId: 16, memberName: '전승우', status: '출석' },
  { id: 157, sessionId: 8, memberId: 17, memberName: '권다인', status: '지각' },
  { id: 158, sessionId: 8, memberId: 18, memberName: '송태민', status: '출석' },
  { id: 159, sessionId: 8, memberId: 19, memberName: '노지현', status: '출석' },
  { id: 160, sessionId: 8, memberId: 20, memberName: '문성호', status: '출석' },
];
