export const notices = [
  {
    id: 1,
    title: '[필독] 2026년 상반기 운영 일정 안내',
    content: '안녕하세요. 2026년 상반기 전체 운영 일정을 공유드립니다. 첨부된 파일을 확인해 주시고, 일정 변경 시 별도 공지 예정입니다. 각 기수별 세션 일정과 장소를 꼼꼼히 확인해 주세요.',
    author: '관리자',
    createdAt: '2026-01-05',
    views: 342,
    isPinned: true,
    attachments: ['2026_상반기_운영일정표.pdf'],
  },
  {
    id: 2,
    title: '[공지] 회비 납부 안내 및 환불 규정',
    content: '각 기수별 회비 납부 기한과 방법을 안내드립니다. 납부 기한을 준수해 주시기 바라며, 환불은 개강일 기준 7일 이내 전액, 이후 50% 환불이 가능합니다. 자세한 내용은 첨부 파일을 참고해 주세요.',
    author: '관리자',
    createdAt: '2026-01-10',
    views: 287,
    isPinned: true,
    attachments: ['회비_납부안내.pdf', '환불규정.docx'],
  },
  {
    id: 3,
    title: '3월 정기 세미나 참석자 모집',
    content: '3월 28일(토) 오후 2시에 정기 세미나가 진행됩니다. 이번 세미나 주제는 "데이터 분석 실무 활용"이며, 외부 연사를 초빙하여 진행합니다. 참석을 원하시는 분은 3월 20일까지 신청해 주세요.',
    author: '김영수',
    createdAt: '2026-03-01',
    views: 156,
    isPinned: false,
    attachments: [],
  },
  {
    id: 4,
    title: '스터디룸 이용 규칙 변경 안내',
    content: '스터디룸 예약 시스템이 변경되었습니다. 기존 선착순 방식에서 사전 예약제로 전환되오니, 홈페이지를 통해 최소 1일 전 예약 바랍니다. 노쇼 3회 이상 시 이용이 제한됩니다.',
    author: '관리자',
    createdAt: '2026-02-15',
    views: 198,
    isPinned: false,
    attachments: ['스터디룸_이용안내.pdf'],
  },
  {
    id: 5,
    title: '우수 수료생 표창 대상자 발표',
    content: '12기 우수 수료생 표창 대상자를 발표합니다. 선정 기준은 출석률 95% 이상, 프로젝트 평가 상위 10% 이내입니다. 해당 대상자분들께는 개별 연락드리겠습니다. 축하드립니다!',
    author: '이정민',
    createdAt: '2026-02-28',
    views: 231,
    isPinned: false,
    attachments: ['우수수료생_명단.xlsx'],
  },
  {
    id: 6,
    title: '14기 모집 시작 안내',
    content: '14기 모집이 시작되었습니다. 모집 기간은 3월 1일부터 3월 31일까지이며, 정원은 25명입니다. 지인 추천 시 회비 10% 할인 혜택이 있으니 많은 관심 부탁드립니다.',
    author: '관리자',
    createdAt: '2026-03-01',
    views: 412,
    isPinned: false,
    attachments: ['14기_모집요강.pdf', '지원서_양식.docx'],
  },
  {
    id: 7,
    title: '네트워킹 행사 후기 및 사진 공유',
    content: '지난 2월 22일 진행된 전체 네트워킹 행사에 참석해 주신 모든 분들께 감사드립니다. 행사 사진과 후기를 공유드리오니 갤러리 게시판에서도 확인 가능합니다.',
    author: '박소현',
    createdAt: '2026-02-25',
    views: 178,
    isPinned: false,
    attachments: [],
  },
  {
    id: 8,
    title: '온라인 강의 플랫폼 접속 안내',
    content: '비대면 세션을 위한 온라인 강의 플랫폼 접속 방법을 안내드립니다. Zoom 링크는 각 세션 시작 30분 전 문자로 발송되며, 접속 장애 시 운영팀으로 연락 주세요.',
    author: '관리자',
    createdAt: '2026-01-20',
    views: 265,
    isPinned: false,
    attachments: ['온라인_접속가이드.pdf'],
  },
  {
    id: 9,
    title: '13기 팀 프로젝트 주제 확정',
    content: '13기 팀 프로젝트 주제가 확정되었습니다. 각 팀별 주제와 멘토 배정 내역을 첨부 파일에서 확인해 주세요. 프로젝트 킥오프 미팅은 4월 첫째 주에 진행됩니다.',
    author: '최현우',
    createdAt: '2026-03-15',
    views: 134,
    isPinned: false,
    attachments: ['13기_프로젝트_주제.xlsx'],
  },
  {
    id: 10,
    title: '설문조사 참여 요청 - 커리큘럼 개선',
    content: '더 나은 교육 과정을 위해 설문조사를 진행합니다. 소요 시간은 약 5분이며, 참여해 주신 분들 중 추첨을 통해 커피 쿠폰을 드립니다. 3월 25일까지 참여 부탁드립니다.',
    author: '관리자',
    createdAt: '2026-03-10',
    views: 89,
    isPinned: false,
    attachments: [],
  },
];

export const materials = [
  {
    id: 1,
    fileName: '1회차_OT_과정소개.pdf',
    sessionId: 1,
    sessionTopic: 'OT 및 과정 소개',
    uploadedAt: '2026-01-15',
    fileSize: '2.5MB',
    fileType: 'PDF',
  },
  {
    id: 2,
    fileName: '2회차_기초이론_강의자료.pptx',
    sessionId: 2,
    sessionTopic: '기초 이론',
    uploadedAt: '2026-01-22',
    fileSize: '8.1MB',
    fileType: 'PPT',
  },
  {
    id: 3,
    fileName: '3회차_실습가이드.pdf',
    sessionId: 3,
    sessionTopic: '실습 1',
    uploadedAt: '2026-01-29',
    fileSize: '1.8MB',
    fileType: 'PDF',
  },
  {
    id: 4,
    fileName: '4회차_심화이론_강의노트.docx',
    sessionId: 4,
    sessionTopic: '심화 이론',
    uploadedAt: '2026-02-05',
    fileSize: '3.2MB',
    fileType: 'DOCX',
  },
  {
    id: 5,
    fileName: '5회차_팀프로젝트_기획서_템플릿.docx',
    sessionId: 5,
    sessionTopic: '팀 프로젝트 기획',
    uploadedAt: '2026-02-12',
    fileSize: '1.1MB',
    fileType: 'DOCX',
  },
  {
    id: 6,
    fileName: '6회차_실습2_데이터셋_안내.pdf',
    sessionId: 6,
    sessionTopic: '실습 2',
    uploadedAt: '2026-02-19',
    fileSize: '4.7MB',
    fileType: 'PDF',
  },
  {
    id: 7,
    fileName: '7회차_중간발표_평가기준.pptx',
    sessionId: 7,
    sessionTopic: '중간 발표',
    uploadedAt: '2026-02-26',
    fileSize: '5.3MB',
    fileType: 'PPT',
  },
  {
    id: 8,
    fileName: '8회차_최종발표_가이드라인.pdf',
    sessionId: 8,
    sessionTopic: '최종 발표 및 수료식',
    uploadedAt: '2026-03-05',
    fileSize: '2.0MB',
    fileType: 'PDF',
  },
];

export const galleryImages = [
  {
    id: 1,
    title: '13기 OT 단체 사진',
    imageUrl: '/assets/images/gallery/img1.jpg',
    albumName: '13기 활동',
    uploadedAt: '2026-01-15',
    description: '13기 오리엔테이션에서 촬영한 단체 사진입니다.',
  },
  {
    id: 2,
    title: '기초 이론 수업 현장',
    imageUrl: '/assets/images/gallery/img2.jpg',
    albumName: '13기 활동',
    uploadedAt: '2026-01-22',
    description: '열정적으로 수업에 참여하는 13기 회원들의 모습.',
  },
  {
    id: 3,
    title: '팀 프로젝트 회의',
    imageUrl: '/assets/images/gallery/img3.jpg',
    albumName: '13기 활동',
    uploadedAt: '2026-02-12',
    description: 'A팀의 프로젝트 기획 회의 장면입니다.',
  },
  {
    id: 4,
    title: '네트워킹 행사 전경',
    imageUrl: '/assets/images/gallery/img4.jpg',
    albumName: '네트워킹',
    uploadedAt: '2026-02-22',
    description: '전체 기수가 모인 네트워킹 행사 전경.',
  },
  {
    id: 5,
    title: '네트워킹 행사 조별 활동',
    imageUrl: '/assets/images/gallery/img5.jpg',
    albumName: '네트워킹',
    uploadedAt: '2026-02-22',
    description: '네트워킹 행사에서 진행된 아이스브레이킹 활동.',
  },
  {
    id: 6,
    title: '12기 수료식',
    imageUrl: '/assets/images/gallery/img6.jpg',
    albumName: '12기 활동',
    uploadedAt: '2025-12-20',
    description: '12기 수료식 및 우수 수료생 시상식.',
  },
  {
    id: 7,
    title: '12기 최종 발표',
    imageUrl: '/assets/images/gallery/img7.jpg',
    albumName: '12기 활동',
    uploadedAt: '2025-12-15',
    description: '12기 최종 프로젝트 발표 현장입니다.',
  },
  {
    id: 8,
    title: '스터디룸 활용 모습',
    imageUrl: '/assets/images/gallery/img8.jpg',
    albumName: '일상',
    uploadedAt: '2026-03-05',
    description: '스터디룸에서 자율 학습 중인 회원들.',
  },
  {
    id: 9,
    title: '외부 연사 초청 특강',
    imageUrl: '/assets/images/gallery/img9.jpg',
    albumName: '특강',
    uploadedAt: '2026-03-10',
    description: '데이터 분석 전문가 초청 특강 현장.',
  },
  {
    id: 10,
    title: '13기 중간 발표',
    imageUrl: '/assets/images/gallery/img10.jpg',
    albumName: '13기 활동',
    uploadedAt: '2026-02-26',
    description: '13기 중간 프로젝트 발표 장면.',
  },
  {
    id: 11,
    title: '운영진 회의',
    imageUrl: '/assets/images/gallery/img11.jpg',
    albumName: '운영',
    uploadedAt: '2026-01-08',
    description: '2026년 상반기 운영 계획 수립을 위한 운영진 회의.',
  },
  {
    id: 12,
    title: '봄맞이 야외 모임',
    imageUrl: '/assets/images/gallery/img12.jpg',
    albumName: '네트워킹',
    uploadedAt: '2026-03-22',
    description: '봄을 맞아 한강에서 진행된 야외 친목 모임.',
  },
];
