export const cohorts = [
  {
    id: 1,
    name: '1기',
    status: '수료',
    startDate: '2024-03-04',
    endDate: '2024-08-30',
    capacity: 30,
    currentCount: 28,
    graduationAttendanceRate: 80,
    manager: '김영호',
    memo: '첫 번째 기수 성공적 운영 완료',
  },
  {
    id: 2,
    name: '2기',
    status: '운영중',
    startDate: '2024-09-02',
    endDate: '2025-02-28',
    capacity: 30,
    currentCount: 25,
    graduationAttendanceRate: 80,
    manager: '이정은',
    memo: '현재 운영 중인 기수',
  },
  {
    id: 3,
    name: '3기',
    status: '모집중',
    startDate: '2025-03-03',
    endDate: '2025-08-29',
    capacity: 30,
    currentCount: 12,
    graduationAttendanceRate: 80,
    manager: '박수현',
    memo: '3기 모집 진행 중 (마감 임박)',
  },
];
