export const events = [
  {
    id: 1,
    name: '리더십 워크숍',
    type: '워크숍',
    date: '2026-04-12',
    location: '서울 강남구 삼성동 코엑스 컨퍼런스룸',
    target: '전체',
    capacity: 80,
    fee: 50000,
    deadline: '2026-04-05',
    description: '차세대 리더를 위한 리더십 역량 강화 워크숍입니다. 외부 전문 강사를 초빙하여 실무 중심의 교육을 진행합니다.',
    status: '모집중',
  },
  {
    id: 2,
    name: '제5회 친선 골프대회',
    type: '골프대회',
    date: '2026-05-09',
    location: '경기도 이천시 사우스스프링스CC',
    target: '골프회',
    capacity: 40,
    fee: 150000,
    deadline: '2026-04-30',
    description: '회원 간 친선 도모를 위한 정기 골프대회입니다. 개인전 및 팀전으로 진행되며 우승자에게 트로피와 상품을 수여합니다.',
    status: '모집중',
  },
  {
    id: 3,
    name: '가을 체육대회',
    type: '체육대회',
    date: '2026-10-17',
    location: '서울 송파구 올림픽공원 체육관',
    target: '전체',
    capacity: 200,
    fee: 20000,
    deadline: '2026-10-10',
    description: '전 회원이 참여하는 연례 체육대회입니다. 족구, 줄다리기, 릴레이 등 다양한 종목으로 진행됩니다.',
    status: '모집중',
  },
  {
    id: 4,
    name: '일본 규슈 해외연수',
    type: '해외연수',
    date: '2026-06-20',
    location: '일본 후쿠오카·나가사키 (3박 4일)',
    target: '25기',
    capacity: 30,
    fee: 1200000,
    deadline: '2026-05-20',
    description: '일본 규슈 지역 기업 방문 및 문화 탐방을 겸한 해외연수입니다. 현지 동문 네트워크와의 교류 프로그램도 포함되어 있습니다.',
    status: '모집중',
  },
  {
    id: 5,
    name: '2025년 송년회',
    type: '송년회',
    date: '2025-12-20',
    location: '서울 중구 더플라자호텔 그랜드볼룸',
    target: '전체',
    capacity: 150,
    fee: 80000,
    deadline: '2025-12-13',
    description: '한 해를 마무리하며 회원 간 감사와 우정을 나누는 송년 행사입니다. 만찬, 공연, 경품 추첨이 진행되었습니다.',
    status: '완료',
  },
  {
    id: 6,
    name: '사진 촬영 특강',
    type: '기타',
    date: '2026-03-08',
    location: '서울 종로구 북촌한옥마을 문화센터',
    target: '트레킹회',
    capacity: 25,
    fee: 30000,
    deadline: '2026-03-01',
    description: '트레킹 활동 시 풍경 사진을 더 잘 찍기 위한 사진 촬영 특강입니다. 전문 사진작가가 카메라 및 스마트폰 촬영 기법을 교육합니다.',
    status: '마감',
  },
]

export const eventParticipants = [
  // 리더십 워크숍 참가자
  { id: 1, eventId: 1, memberId: 101, memberName: '김정호', status: '확정', attendanceChecked: false },
  { id: 2, eventId: 1, memberId: 102, memberName: '박성민', status: '확정', attendanceChecked: false },
  { id: 3, eventId: 1, memberId: 103, memberName: '이수진', status: '신청', attendanceChecked: false },
  { id: 4, eventId: 1, memberId: 109, memberName: '정태영', status: '취소', attendanceChecked: false },
  { id: 5, eventId: 1, memberId: 113, memberName: '배준서', status: '신청', attendanceChecked: false },
  // 골프대회 참가자
  { id: 6, eventId: 2, memberId: 102, memberName: '박성민', status: '확정', attendanceChecked: false },
  { id: 7, eventId: 2, memberId: 109, memberName: '정태영', status: '확정', attendanceChecked: false },
  { id: 8, eventId: 2, memberId: 110, memberName: '강민수', status: '신청', attendanceChecked: false },
  { id: 9, eventId: 2, memberId: 111, memberName: '서영진', status: '신청', attendanceChecked: false },
  // 체육대회 참가자
  { id: 10, eventId: 3, memberId: 101, memberName: '김정호', status: '신청', attendanceChecked: false },
  { id: 11, eventId: 3, memberId: 105, memberName: '한상우', status: '신청', attendanceChecked: false },
  { id: 12, eventId: 3, memberId: 114, memberName: '송지원', status: '신청', attendanceChecked: false },
  // 해외연수 참가자
  { id: 13, eventId: 4, memberId: 106, memberName: '윤재혁', status: '확정', attendanceChecked: false },
  { id: 14, eventId: 4, memberId: 107, memberName: '장미란', status: '신청', attendanceChecked: false },
  { id: 15, eventId: 4, memberId: 115, memberName: '류동혁', status: '취소', attendanceChecked: false },
  // 송년회 참가자
  { id: 16, eventId: 5, memberId: 101, memberName: '김정호', status: '확정', attendanceChecked: true },
  { id: 17, eventId: 5, memberId: 102, memberName: '박성민', status: '확정', attendanceChecked: true },
  { id: 18, eventId: 5, memberId: 103, memberName: '이수진', status: '확정', attendanceChecked: true },
  { id: 19, eventId: 5, memberId: 104, memberName: '최영희', status: '확정', attendanceChecked: false },
  { id: 20, eventId: 5, memberId: 110, memberName: '강민수', status: '취소', attendanceChecked: false },
  // 사진 촬영 특강 참가자
  { id: 21, eventId: 6, memberId: 103, memberName: '이수진', status: '확정', attendanceChecked: true },
  { id: 22, eventId: 6, memberId: 113, memberName: '배준서', status: '확정', attendanceChecked: true },
  { id: 23, eventId: 6, memberId: 114, memberName: '송지원', status: '확정', attendanceChecked: true },
  { id: 24, eventId: 6, memberId: 116, memberName: '허윤아', status: '확정', attendanceChecked: false },
]
