export const members = [
  // ===== 1기 (cohortId: 1) =====
  {
    id: 1,
    name: '김민수',
    photo: null,
    company: '삼성전자',
    position: '부장',
    email: 'minsu.kim@samsung.com',
    phone: '010-1234-5678',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [1, 3],
    memo: '우수 수료자',
    isActive: true,
    createdAt: '2024-03-01',
  },
  {
    id: 2,
    name: '이서연',
    photo: null,
    company: 'LG에너지솔루션',
    position: '차장',
    email: 'seoyeon.lee@lgensol.com',
    phone: '010-2345-6789',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [2],
    memo: '',
    isActive: true,
    createdAt: '2024-03-01',
  },
  {
    id: 3,
    name: '박준호',
    photo: null,
    company: 'SK하이닉스',
    position: '과장',
    email: 'junho.park@skhynix.com',
    phone: '010-3456-7890',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [1],
    memo: '팀 프로젝트 리더',
    isActive: true,
    createdAt: '2024-03-02',
  },
  {
    id: 4,
    name: '최유진',
    photo: null,
    company: '현대자동차',
    position: '대리',
    email: 'yujin.choi@hyundai.com',
    phone: '010-4567-8901',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [2, 3],
    memo: '',
    isActive: true,
    createdAt: '2024-03-02',
  },
  {
    id: 5,
    name: '정하은',
    photo: null,
    company: '네이버',
    position: '팀장',
    email: 'haeun.jung@naver.com',
    phone: '010-5678-9012',
    cohortId: 1,
    cohortName: '1기',
    status: '휴학',
    clubs: [],
    memo: '개인 사정으로 휴학',
    isActive: false,
    createdAt: '2024-03-03',
  },
  {
    id: 6,
    name: '강도윤',
    photo: null,
    company: '카카오',
    position: '부장',
    email: 'doyun.kang@kakao.com',
    phone: '010-6789-0123',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [1, 2],
    memo: '',
    isActive: true,
    createdAt: '2024-03-03',
  },
  {
    id: 7,
    name: '윤지아',
    photo: null,
    company: '포스코',
    position: '차장',
    email: 'jia.yoon@posco.com',
    phone: '010-7890-1234',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [3],
    memo: '최우수 발표상 수상',
    isActive: true,
    createdAt: '2024-03-04',
  },
  {
    id: 8,
    name: '임태현',
    photo: null,
    company: '롯데케미칼',
    position: '과장',
    email: 'taehyun.lim@lottechem.com',
    phone: '010-8901-2345',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [1],
    memo: '',
    isActive: true,
    createdAt: '2024-03-04',
  },
  {
    id: 9,
    name: '한소율',
    photo: null,
    company: 'CJ제일제당',
    position: '대리',
    email: 'soyul.han@cj.com',
    phone: '010-9012-3456',
    cohortId: 1,
    cohortName: '1기',
    status: '수료',
    clubs: [2, 3],
    memo: '',
    isActive: true,
    createdAt: '2024-03-05',
  },
  // ===== 2기 (cohortId: 2) =====
  {
    id: 10,
    name: '서예준',
    photo: null,
    company: '삼성SDS',
    position: '과장',
    email: 'yejun.seo@samsungsds.com',
    phone: '010-1122-3344',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [1],
    memo: '',
    isActive: true,
    createdAt: '2024-09-01',
  },
  {
    id: 11,
    name: '오수빈',
    photo: null,
    company: 'KT',
    position: '부장',
    email: 'subin.oh@kt.com',
    phone: '010-2233-4455',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [2, 3],
    memo: '분반장',
    isActive: true,
    createdAt: '2024-09-01',
  },
  {
    id: 12,
    name: '신동현',
    photo: null,
    company: 'LG전자',
    position: '차장',
    email: 'donghyun.shin@lge.com',
    phone: '010-3344-5566',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [1, 2],
    memo: '',
    isActive: true,
    createdAt: '2024-09-02',
  },
  {
    id: 13,
    name: '배지현',
    photo: null,
    company: '한화솔루션',
    position: '대리',
    email: 'jihyun.bae@hanwha.com',
    phone: '010-4455-6677',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [3],
    memo: '',
    isActive: true,
    createdAt: '2024-09-02',
  },
  {
    id: 14,
    name: '조민재',
    photo: null,
    company: '두산에너빌리티',
    position: '과장',
    email: 'minjae.cho@doosan.com',
    phone: '010-5566-7788',
    cohortId: 2,
    cohortName: '2기',
    status: '휴학',
    clubs: [],
    memo: '해외 출장으로 인한 휴학',
    isActive: false,
    createdAt: '2024-09-03',
  },
  {
    id: 15,
    name: '권나연',
    photo: null,
    company: '아모레퍼시픽',
    position: '팀장',
    email: 'nayeon.kwon@amorepacific.com',
    phone: '010-6677-8899',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [1, 3],
    memo: '',
    isActive: true,
    createdAt: '2024-09-03',
  },
  {
    id: 16,
    name: '황성민',
    photo: null,
    company: 'GS칼텍스',
    position: '부장',
    email: 'sungmin.hwang@gscaltex.com',
    phone: '010-7788-9900',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [2],
    memo: '기업 협력 프로젝트 담당',
    isActive: true,
    createdAt: '2024-09-04',
  },
  {
    id: 17,
    name: '문채원',
    photo: null,
    company: '셀트리온',
    position: '차장',
    email: 'chaewon.moon@celltrion.com',
    phone: '010-8899-0011',
    cohortId: 2,
    cohortName: '2기',
    status: '재학',
    clubs: [1, 2, 3],
    memo: '',
    isActive: true,
    createdAt: '2024-09-04',
  },
  // ===== 3기 (cohortId: 3) =====
  {
    id: 18,
    name: '송이준',
    photo: null,
    company: '현대모비스',
    position: '과장',
    email: 'ijun.song@mobis.com',
    phone: '010-1010-2020',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [1],
    memo: '',
    isActive: true,
    createdAt: '2025-03-01',
  },
  {
    id: 19,
    name: '양하린',
    photo: null,
    company: 'SK텔레콤',
    position: '대리',
    email: 'harin.yang@sktelecom.com',
    phone: '010-2020-3030',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [2],
    memo: '',
    isActive: true,
    createdAt: '2025-03-01',
  },
  {
    id: 20,
    name: '류건우',
    photo: null,
    company: '삼성바이오로직스',
    position: '부장',
    email: 'gunwoo.ryu@samsungbio.com',
    phone: '010-3030-4040',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [3],
    memo: '바이오 분야 전문가',
    isActive: true,
    createdAt: '2025-03-02',
  },
  {
    id: 21,
    name: '노은서',
    photo: null,
    company: '쿠팡',
    position: '팀장',
    email: 'eunseo.noh@coupang.com',
    phone: '010-4040-5050',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [1, 2],
    memo: '',
    isActive: true,
    createdAt: '2025-03-02',
  },
  {
    id: 22,
    name: '하시우',
    photo: null,
    company: '카카오뱅크',
    position: '차장',
    email: 'siwoo.ha@kakaobank.com',
    phone: '010-5050-6060',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [],
    memo: '핀테크 분야 관심',
    isActive: true,
    createdAt: '2025-03-03',
  },
  {
    id: 23,
    name: '전다은',
    photo: null,
    company: '한국전력공사',
    position: '과장',
    email: 'daeun.jeon@kepco.com',
    phone: '010-6060-7070',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [2, 3],
    memo: '',
    isActive: true,
    createdAt: '2025-03-03',
  },
  {
    id: 24,
    name: '장우진',
    photo: null,
    company: '토스',
    position: '대리',
    email: 'woojin.jang@toss.im',
    phone: '010-7070-8080',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [1],
    memo: '',
    isActive: true,
    createdAt: '2025-03-04',
  },
  {
    id: 25,
    name: '남지우',
    photo: null,
    company: '배달의민족',
    position: '과장',
    email: 'jiwoo.nam@woowahan.com',
    phone: '010-8080-9090',
    cohortId: 3,
    cohortName: '3기',
    status: '재학',
    clubs: [3],
    memo: '플랫폼 비즈니스 전문',
    isActive: true,
    createdAt: '2025-03-04',
  },
];
