export const sessions = [
  // ===== 1기 세션 (완료) =====
  {
    id: 1,
    date: '2024-03-11',
    startTime: '09:00',
    endTime: '12:00',
    location: '서울캠퍼스 대강의실 A',
    instructorId: 1,
    instructorName: '홍길동',
    topic: '디지털 전환 전략과 리더십',
    cohortId: 1,
    cohortName: '1기',
    status: '완료',
    memo: '오리엔테이션 포함',
  },
  {
    id: 2,
    date: '2024-04-08',
    startTime: '13:00',
    endTime: '17:00',
    location: '서울캠퍼스 세미나실 B',
    instructorId: 2,
    instructorName: '김태영',
    topic: 'AI/빅데이터 기반 경영 의사결정',
    cohortId: 1,
    cohortName: '1기',
    status: '완료',
    memo: '실습 장비 준비 완료',
  },
  {
    id: 3,
    date: '2024-05-13',
    startTime: '09:00',
    endTime: '12:00',
    location: '판교 혁신센터 3층',
    instructorId: 3,
    instructorName: '이미래',
    topic: 'ESG 경영과 지속가능성',
    cohortId: 1,
    cohortName: '1기',
    status: '완료',
    memo: '',
  },
  {
    id: 4,
    date: '2024-06-10',
    startTime: '14:00',
    endTime: '18:00',
    location: '서울캠퍼스 대강의실 A',
    instructorId: 4,
    instructorName: '박혁신',
    topic: '글로벌 비즈니스 협상 전략',
    cohortId: 1,
    cohortName: '1기',
    status: '완료',
    memo: '외부 초청 강연 병행',
  },
  // ===== 2기 세션 (완료 + 예정) =====
  {
    id: 5,
    date: '2024-09-09',
    startTime: '09:00',
    endTime: '12:00',
    location: '서울캠퍼스 대강의실 A',
    instructorId: 1,
    instructorName: '홍길동',
    topic: '디지털 전환 전략과 리더십',
    cohortId: 2,
    cohortName: '2기',
    status: '완료',
    memo: '2기 개강 세션',
  },
  {
    id: 6,
    date: '2024-10-14',
    startTime: '13:00',
    endTime: '17:00',
    location: '판교 혁신센터 3층',
    instructorId: 5,
    instructorName: '정수진',
    topic: '조직문화 혁신과 변화관리',
    cohortId: 2,
    cohortName: '2기',
    status: '완료',
    memo: '',
  },
  {
    id: 7,
    date: '2024-11-11',
    startTime: '09:00',
    endTime: '12:00',
    location: '서울캠퍼스 세미나실 B',
    instructorId: 2,
    instructorName: '김태영',
    topic: '데이터 기반 마케팅 전략',
    cohortId: 2,
    cohortName: '2기',
    status: '완료',
    memo: '사례 중심 강의',
  },
  {
    id: 8,
    date: '2024-12-09',
    startTime: '14:00',
    endTime: '18:00',
    location: '서울캠퍼스 대강의실 A',
    instructorId: 6,
    instructorName: '최원석',
    topic: '재무전략과 기업가치 평가',
    cohortId: 2,
    cohortName: '2기',
    status: '완료',
    memo: '',
  },
  {
    id: 9,
    date: '2025-01-13',
    startTime: '09:00',
    endTime: '12:00',
    location: '판교 혁신센터 3층',
    instructorId: 3,
    instructorName: '이미래',
    topic: 'ESG 경영과 지속가능성',
    cohortId: 2,
    cohortName: '2기',
    status: '취소',
    memo: '강사 사정으로 취소 - 추후 보강 예정',
  },
  // ===== 3기 세션 (예정) =====
  {
    id: 10,
    date: '2025-03-10',
    startTime: '09:00',
    endTime: '12:00',
    location: '서울캠퍼스 대강의실 A',
    instructorId: 1,
    instructorName: '홍길동',
    topic: '디지털 전환 전략과 리더십',
    cohortId: 3,
    cohortName: '3기',
    status: '완료',
    memo: '3기 개강 세션',
  },
  {
    id: 11,
    date: '2025-04-14',
    startTime: '13:00',
    endTime: '17:00',
    location: '서울캠퍼스 세미나실 B',
    instructorId: 4,
    instructorName: '박혁신',
    topic: '혁신적 사고와 문제해결',
    cohortId: 3,
    cohortName: '3기',
    status: '예정',
    memo: '',
  },
  {
    id: 12,
    date: '2025-05-12',
    startTime: '09:00',
    endTime: '12:00',
    location: '판교 혁신센터 3층',
    instructorId: 5,
    instructorName: '정수진',
    topic: '조직문화 혁신과 변화관리',
    cohortId: 3,
    cohortName: '3기',
    status: '예정',
    memo: '워크숍 형태로 진행 예정',
  },
];

export const instructors = [
  {
    id: 1,
    name: '홍길동',
    organization: '서울대학교 경영대학',
    specialty: '디지털 전환 전략',
    phone: '010-1111-2222',
    email: 'gildong.hong@snu.ac.kr',
    sessionHistory: [1, 5, 10],
  },
  {
    id: 2,
    name: '김태영',
    organization: 'KAIST 경영공학부',
    specialty: 'AI/빅데이터 경영',
    phone: '010-2222-3333',
    email: 'taeyoung.kim@kaist.ac.kr',
    sessionHistory: [2, 7],
  },
  {
    id: 3,
    name: '이미래',
    organization: '한국ESG연구원',
    specialty: 'ESG 경영 / 지속가능성',
    phone: '010-3333-4444',
    email: 'mirae.lee@esginstitute.kr',
    sessionHistory: [3, 9],
  },
  {
    id: 4,
    name: '박혁신',
    organization: '연세대학교 국제대학원',
    specialty: '글로벌 비즈니스 / 혁신경영',
    phone: '010-4444-5555',
    email: 'hyuksin.park@yonsei.ac.kr',
    sessionHistory: [4, 11],
  },
  {
    id: 5,
    name: '정수진',
    organization: '맥킨지 코리아',
    specialty: '조직문화 / 변화관리',
    phone: '010-5555-6666',
    email: 'sujin.jung@mckinsey.com',
    sessionHistory: [6, 12],
  },
  {
    id: 6,
    name: '최원석',
    organization: '고려대학교 경영대학',
    specialty: '재무전략 / 기업가치',
    phone: '010-6666-7777',
    email: 'wonseok.choi@korea.ac.kr',
    sessionHistory: [8],
  },
];
